//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10eRg2Moveit
{
    [Serializable]
    public class PoseEstimationServiceRequest : Message
    {
        public const string k_RosMessageName = "ur10e_rg2_moveit/PoseEstimationService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public PoseEstimationServiceRequest()
        {
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public PoseEstimationServiceRequest(Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static PoseEstimationServiceRequest Deserialize(MessageDeserializer deserializer) => new PoseEstimationServiceRequest(deserializer);

        private PoseEstimationServiceRequest(MessageDeserializer deserializer)
        {
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "PoseEstimationServiceRequest: " +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
